baseURL = "https://bitecross.co.uk/"
languageCode = "en-uk"
title = "Whitecross Street Market"
theme = "hugrid"


# Site settings
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-55020274-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
title = "Whitecross Street Food Market"
subtitle = "Every weekday lunchtime on [whitecross street](https://goo.gl/maps/9y5GTSCi6K2art888). Find out more about this year's Whitecross Street Party (9-10 July 2022) [here](https://www.wxstreetparty.co.uk). "
    author = "Harald"
    description = "Weekday London City Food market, at Whitecross Street.  "
    keywords = "London, Food Market, Whitecross Street Market"

    # Body background color

    # Preview container button text
    buttontext = "Website/Social"

    # Footer text
    footertext = "More info on the [Facebook Group](https://en-gb.facebook.com/groups/77923624125/). Check Islington Council's [website](https://www.islington.gov.uk/business/licences-permits-registration/trading-on-our-streets/market-trading) or [email them](mailto:street.trading@islington.gov.uk) to apply for a pitch. <br /> [Enquire](mailto:contact@bitecross.co.uk) about paid advertising on this site.  Suggest changes on [github](https://github.com/bitecross/bitecross.github.io)."

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
custom_css = ['css/bitecross.css']
